### ISSUE TITLE
Common ground

### ISSUE THREAD

**Issue by LegitTalon** [Denver-Devs/the-road-to-frp#3]
It would be helpful to figure out where to start. I am thinking that Angular and MVC is maybe familiar to all of us and we can move from there to React FLUX (which is a step in the direction of FRP)?

Thoughts?

**Comment by aaronagray** [comment]
+1 for react. -1 for Angular. :)

Does this group still meet up / work on things? I had a functional epiphany last week and would love to discuss. :P

**Comment by LegitTalon** [comment]
@aaronagray It currently exists as an asynchronous digital blob. I'd like to formalize some sort of irl "study night". I think this thread will assist with that by helping us understand where to start. Crafting an ad-hoc curriculum by pushing what we know towards what's new and unfamiliar.

**Comment by aaronagray** [comment]
Word. Are you free next Wednesday night? We can start an informal gathering in the Denver Galvanize atrium next week.

**Comment by LegitTalon** [comment]
Sounds fantastic. I'll be there. Mind if I extend the invite to the #functional-reactive channel in the slack?

**Comment by aaronagray** [comment]
Woot! How many people do you think will make it? If it's < 10, then we should still be okay to use the atrium or classroom after hours. 

Also, I'm thinking 6pm?

**Comment by LegitTalon** [comment]
Great first meetup.
